---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_plot
    #    platform: linux/amd64
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/opt/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /opt/freqtrade/user_data/logs/freqtrade.log
      --config /opt/freqtrade/user_data/config/master.json
      --config /opt/freqtrade/user_data/config/SmaRsi_8082.json
      --config /opt/freqtrade/user_data/config/docker.json
